-- Add Brunch UX/UI profile sources requested by admin.
-- Profile URLs are allowed because cron now auto-discovers alternate RSS/Atom links.
INSERT INTO article_sources (name, url, category, keywords, source_type, is_active)
VALUES
  ('브런치 @inaroundthenest', 'https://brunch.co.kr/@inaroundthenest', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @daisyuxui', 'https://brunch.co.kr/@daisyuxui', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @uxminxu', 'https://brunch.co.kr/@uxminxu', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @figmaster', 'https://brunch.co.kr/@figmaster', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @cliche-cliche', 'https://brunch.co.kr/@cliche-cliche', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @00mm', 'https://brunch.co.kr/@00mm', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @da18ef10e6c849f', 'https://brunch.co.kr/@da18ef10e6c849f', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @grit-han', 'https://brunch.co.kr/@grit-han', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @lovelylucia', 'https://brunch.co.kr/@lovelylucia', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @greening', 'https://brunch.co.kr/@greening', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @design-melon', 'https://brunch.co.kr/@design-melon', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @rididesign', 'https://brunch.co.kr/@rididesign', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @11design', 'https://brunch.co.kr/@11design', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @geunbae', 'https://brunch.co.kr/@geunbae', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @ebprux', 'https://brunch.co.kr/@ebprux', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @masaru3595', 'https://brunch.co.kr/@masaru3595', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @product-design', 'https://brunch.co.kr/@product-design', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @786c6f7068204f0', 'https://brunch.co.kr/@786c6f7068204f0', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @theopenproduct', 'https://brunch.co.kr/@theopenproduct', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @uxn00b', 'https://brunch.co.kr/@uxn00b', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @justtryux', 'https://brunch.co.kr/@justtryux', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @yewooonon', 'https://brunch.co.kr/@yewooonon', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @minjay-kim', 'https://brunch.co.kr/@minjay-kim', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @eunyoung42', 'https://brunch.co.kr/@eunyoung42', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @uxui-neo', 'https://brunch.co.kr/@uxui-neo', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @yukiepark', 'https://brunch.co.kr/@yukiepark', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @vivishin', 'https://brunch.co.kr/@vivishin', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @designerjung', 'https://brunch.co.kr/@designerjung', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @ashashash', 'https://brunch.co.kr/@ashashash', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @needesign', 'https://brunch.co.kr/@needesign', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @uxdesign', 'https://brunch.co.kr/@uxdesign', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @sangster', 'https://brunch.co.kr/@sangster', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @kennyhong', 'https://brunch.co.kr/@kennyhong', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @andrewyhc', 'https://brunch.co.kr/@andrewyhc', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @userhabit', 'https://brunch.co.kr/@userhabit', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @scottim', 'https://brunch.co.kr/@scottim', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @windydog', 'https://brunch.co.kr/@windydog', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @creative', 'https://brunch.co.kr/@creative', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @kakaoux', 'https://brunch.co.kr/@kakaoux', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @meanimize', 'https://brunch.co.kr/@meanimize', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @suyoung', 'https://brunch.co.kr/@suyoung', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @yunjungseo', 'https://brunch.co.kr/@yunjungseo', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @sapu0000', 'https://brunch.co.kr/@sapu0000', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @speedlyhv1tx', 'https://brunch.co.kr/@speedlyhv1tx', 'UX 디자인', '{}', 'seed', TRUE),
  ('브런치 @jbkim8905', 'https://brunch.co.kr/@jbkim8905', 'UX 디자인', '{}', 'seed', TRUE)
ON CONFLICT (url) DO UPDATE
SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  keywords = EXCLUDED.keywords,
  source_type = EXCLUDED.source_type,
  is_active = TRUE;
